// drizzle/schema-ai.ts
//
// AI-buddy + billing tables, split from schema.ts (max-lines). Re-exported by
// schema.ts (`export * from "./schema-ai"`), so app imports and drizzle-kit's
// single-entry config are unchanged. References to users/oab_questions are lazy
// (arrow callbacks), so the circular import with schema.ts is safe.

import {
  check,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import type { CoachDigest, CoachStudentData } from "../shared/domain/ai-coach";
import { users, oabQuestions } from "./schema";

// Same four system audit columns as schema.ts (kept local — importing the
// non-exported const would require widening schema.ts's surface).
const systemFields = {
  createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow().notNull(),
  createdBy: uuid("created_by"),
  lastUpdAt: timestamp("last_upd_at", { withTimezone: true, mode: "string" })
    .defaultNow()
    .notNull(),
  lastUpdBy: uuid("last_upd_by"),
};

// ─── Monetization — S1 + S2 ────────────────────────────────────────────────

// Active subscription per user. One row per user; status tracks the lifecycle.
// provider_ref / provider_sub_id are nullable placeholders for a future gateway.
// Plan and period dates enable the anniversary-based allowance reset in S3.
export const subscriptions = pgTable(
  "subscriptions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .unique()
      .references(() => users.id, { onDelete: "cascade" }),
    plan: text("plan").notNull(), // LOV code: 'free' | 'paid' (admin-editable)
    status: text("status").notNull(), // 'active' | 'canceled' | 'past_due'
    currentPeriodStart: timestamp("current_period_start", {
      withTimezone: true,
      mode: "string",
    }).notNull(),
    currentPeriodEnd: timestamp("current_period_end", {
      withTimezone: true,
      mode: "string",
    }).notNull(),
    // Gateway placeholders — nullable until payment integration (S-later).
    providerRef: text("provider_ref"),
    providerSubId: text("provider_sub_id"),
    ...systemFields,
  },
  (t) => [index("idx_subscriptions_user").on(t.userId)],
);

// NOTE (D4, epic #50 — no-legacy cutover): the old separate allowance rail table
// and the free-tier daily counter table are DELETED. "Allowance" is now
// `source=subscription` grants in the ONE unified ledger
// (credit_balances/credit_ledger), and admission reads the unified balance (no
// free-tier daily counter). Their DROP migration is generated by `pnpm db:generate`.

// ───────────────────────────────────────────────────────────────────────────

// Per-question AI tutor thread. Stateless one-shots server-side; rows exist so
// the conversation renders as a thread and survives navigation. Assistant text
// is only written by tutorFinalize from the relay result (never client-supplied).
export const aiTutorMessages = pgTable(
  "ai_tutor_messages",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    questionId: text("question_id")
      .notNull()
      .references(() => oabQuestions.id),
    role: text("role").notNull(), // 'user' | 'assistant'
    mode: text("mode"), // TutorMode on user turns; null on assistant turns
    content: text("content").notNull(),
    ...systemFields,
  },
  (t) => [index("idx_ai_tutor_user_question").on(t.userId, t.questionId)],
);

// Cached weak-point coach digests — one row per generation, newest wins. Only
// coach.finalize writes the digest (relay-authored, never client-supplied);
// statsSnapshot = the aggregates it was built from (display/debug).
export const aiCoachDigests = pgTable(
  "ai_coach_digests",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    digest: jsonb("digest").$type<CoachDigest>().notNull(),
    statsSnapshot: jsonb("stats_snapshot").$type<CoachStudentData>(),
    ...systemFields,
  },
  (t) => [index("idx_ai_coach_user_created").on(t.userId, t.createdAt)],
);

// Coupon-based grants — the ONLY way a user gains allowance/credits/subscription
// until a real purchase flow exists (auto signup grants are farmable; maggie #126).
// Global table; `redeemedCount` is the lockable row for the atomic per-coupon cap
// (conditional UPDATE ... WHERE redeemed_count < max_redemptions RETURNING) —
// never derive it by counting ledger rows.
//
// kind: 'credits'      — grants valueCredits to credit_ledger (legacy default)
//       'allowance'    — grants valueUnits (source=subscription) via grantAllowance
//       'subscription' — activates a subscription period via grantSubscription
//
// valueCredits: used for kind='credits' (credits granted).
// valueUnits:   used for kind='allowance' (allowance units granted).
// valuePeriodMonths: used for kind='subscription' (months granted).
// Only the relevant value field is required per kind; others may be 0/null.
export const coupons = pgTable(
  "coupons",
  {
    code: text("code").primaryKey(), // XXXX-XXXX, uppercase
    kind: text("kind").notNull().default("credits"), // 'credits' | 'allowance' | 'subscription'
    valueCredits: integer("value_credits").notNull().default(0),
    valueUnits: integer("value_units").notNull().default(0), // allowance units (kind='allowance')
    valuePeriodMonths: integer("value_period_months").notNull().default(0), // months (kind='subscription')
    maxRedemptions: integer("max_redemptions").notNull().default(1),
    redeemedCount: integer("redeemed_count").notNull().default(0),
    expiresAt: timestamp("expires_at", { withTimezone: true, mode: "string" }),
    note: text("note"),
    ...systemFields,
  },
  (t) => [
    // DB-level guard: only the three known kind values are accepted (F2, issue #53).
    check("coupons_kind_check", sql`${t.kind} IN ('credits', 'allowance', 'subscription')`),
  ],
);

// Pay-as-you-go credit ledger — balance = SUM(delta). ref_id = idempotency key
// (jobId spend / refund:<jobId> / coupon:<code>:<userId>); unique index bars doubles.
//
// D1 (epic #50) — this is being unified into the SINGLE append-only money ledger.
// New columns are ADDITIVE (the legacy `delta`/`action` stay for the current
// rails until D2 migrates them):
//   - deltaCents: signed cents in the unified engine (positive grant/purchase,
//     negative consumption/expiry). Nullable until backfill populates it.
//   - kind: canonical ledger kind — grant | purchase | refund | consumption |
//     adjustment | expiry. `expiry` is the append-only NEGATIVE reset row (D2).
//   - source: open string (purchase | coupon | admin | subscription | …).
//     Unlisted source → DEFAULT mult 100 (1×).
// A CHECK constrains kind to the known set; source is intentionally unconstrained
// (open-string, config-driven multiplier per source in credit_config).
export const creditLedger = pgTable(
  "credit_ledger",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    delta: integer("delta").notNull(), // LEGACY signed credits (pre-D1 rails)
    action: text("action").notNull(), // LEGACY LedgerAction (pre-D1 rails)
    // ── D1 unified-ledger columns (additive) ──
    deltaCents: integer("delta_cents"), // signed cents — the invariant's term
    kind: text("kind"), // canonical ledger kind (see CHECK below)
    source: text("source"), // open-string funding/spend source
    refId: text("ref_id").unique(), // idempotency key — nullable for manual grants
    note: text("note"),
    ...systemFields,
  },
  (t) => [
    index("idx_credit_ledger_user_created").on(t.userId, t.createdAt),
    // D1: constrain the canonical kind to the known set (open source stays free).
    // NULL is allowed so legacy rows (pre-backfill) do not violate the check.
    check(
      "credit_ledger_kind_check",
      sql`${t.kind} IS NULL OR ${t.kind} IN ('grant', 'purchase', 'refund', 'consumption', 'adjustment', 'expiry')`,
    ),
  ],
);

// ─── D1 unified credit engine — materialized balance, charges, config ───────

// Materialized per-user balance (1:1 with users). The invariant this table
// enforces: balance_cents == SUM(credit_ledger.delta_cents) for the user, kept
// true because the money core (api/lib/credit-charge.ts) mutates this row and
// appends the ledger row in the SAME transaction, always via
// INSERT … ON CONFLICT (user_id) DO UPDATE — never a bare UPDATE.
//   - balance_cents: whole-cent authoritative balance (may be negative — real).
//   - bag_cents: OFF-ledger fractional carry (numeric(12,4)); sub-cent charges
//     accumulate here until floor >= 1¢ flushes one consumption row.
//   - reference_cents: wallet-gauge anchor — snapshot of balance at last positive
//     money-in (grant/purchase); the D4 fuel gauge is balance/reference.
export const creditBalances = pgTable("credit_balances", {
  userId: uuid("user_id")
    .primaryKey()
    .references(() => users.id, { onDelete: "cascade" }),
  balanceCents: integer("balance_cents").notNull().default(0),
  bagCents: numeric("bag_cents", { precision: 12, scale: 4 }).notNull().default("0"),
  referenceCents: integer("reference_cents").notNull().default(0),
  ...systemFields,
});

// Idempotent charge attribution. One row per settled charge; ref_id is the PK so
// a replay is absorbed by INSERT … ON CONFLICT (ref_id) DO NOTHING RETURNING —
// an empty RETURNING means the charge already happened, so the bag does NOT
// re-accumulate. raw_cents/owed_cents are the pre/post-multiplier audit trail.
export const creditCharges = pgTable(
  "credit_charges",
  {
    refId: text("ref_id").primaryKey(), // idempotency key = charge identity
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    source: text("source").notNull(), // open-string source (drives multiplier)
    rawCents: numeric("raw_cents", { precision: 12, scale: 4 }).notNull(), // pre-multiplier cost
    owedCents: numeric("owed_cents", { precision: 12, scale: 4 }).notNull(), // post-multiplier fractional owed
    ...systemFields,
  },
  (t) => [index("idx_credit_charges_user").on(t.userId)],
);

// Single-use consume marker for a relay AI job (Codex #61 round 3). Each done relay
// job may back EXACTLY ONE persisted AI output, bound to ONE target record. Without
// this, a done jobId could be replayed with a different answerId/questionId to
// persist AI fields onto many records while charge()'s refId-idempotency blocked the
// extra charges → one paid job backing many outputs. The consume proc INSERTs one
// row here (ref_id = the charge refId, so consumption + charge share one identity) in
// the SAME transaction as the persist + charge; a later consume of the same jobId is
// idempotent when it targets the SAME record (target_id matches) and REJECTED when it
// targets a different one. Per-user owned (add a TABLE_SCOPE entry in api/db/scope.ts).
export const aiJobConsumption = pgTable(
  "ai_job_consumption",
  {
    // Idempotency identity — the SAME string charge() keys on (e.g. `grade:<jobId>`
    // / `explain:admin:<jobId>`), so persist + marker + charge form one identity.
    refId: text("ref_id").primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    jobId: text("job_id").notNull(), // the relay jobId this consume settled
    // The record the AI output was persisted onto (answerId / questionId). A replay
    // of the same jobId onto a DIFFERENT target_id is rejected (single-use binding).
    targetId: text("target_id").notNull(),
    source: text("source").notNull(), // door source (grade | explanation | …)
    ...systemFields,
  },
  (t) => [index("idx_ai_job_consumption_user").on(t.userId)],
);

// Global admin config for the money engine — every live knob is a DB row, no
// redeploy to tune. Scoped GLOBAL (like pricing_config): not user-owned.
//   key examples: 'mult.<source>' (×100 int; 100 = 1×, absent → 100),
//     'rollover.<source>' (0/1 bool as int), 'expiry_months.<source>' (int N).
//   value_int is a plain integer — fixed-point ×100 for multipliers, bool-as-int
//     for flags, month count for expiry. No float knobs (float drift avoided).
export const creditConfig = pgTable("credit_config", {
  key: text("key").primaryKey(),
  valueInt: integer("value_int").notNull(),
  description: text("description"),
  ...systemFields,
});

// ─── Admin-editable pricing / config table — S5 ────────────────────────────
//
// Every number that governs pricing, allowance sizes, and pack sizes lives HERE
// as a DB row — never hardcoded in source. Rows are editable by an admin with
// NO redeploy. The system MUST refuse to serve a live price while `realCostPerUnit`
// is null (unset-real-cost guard in api/lib/pricing-config.ts).
//
// key examples (seed rows in db:seed-pricing-config when eval is done):
//   'plan_price_brl'         — monthly subscription price in BRL (centavos)
//   'monthly_allowance_units'— allowance units granted per subscription period
//   'free_daily_limit'       — free-tier core AI uses per day (overrides constant)
//   'allowance_pack_units'   — units in a top-up allowance pack
//   'credit_pack_size'       — credits in a standard credit pack
//   'real_cost_per_unit'     — actual cost (BRL, 4dp) per allowance unit from eval
//
// realCostPerUnit is the eval-seeded anchor. Until it is set, pricing endpoints
// must return an error rather than a stale/zero value (see unset guard).
// numericValue uses NUMERIC(18,4) for BRL-scale precision.
export const pricingConfig = pgTable("pricing_config", {
  key: text("key").primaryKey(), // config key (see examples above)
  numericValue: numeric("numeric_value", { precision: 18, scale: 4 }), // nullable until seeded
  textValue: text("text_value"), // for non-numeric config (e.g. feature flags)
  description: text("description"), // human-readable; admin UI tooltip
  ...systemFields,
});
