// drizzle/schema.ts
//
// Single source of truth for the LexFlow database (PostgreSQL on the shared
// mrhewbuc-rds instance, database `lexflow`).
//
// Model: single-user B2C. `users` rows are individual students linked to Clerk
// via `external_id`. `oab_questions` is a global public catalog. Every other
// table is owned by exactly one user (`user_id` FK) — scoping is enforced in
// the app via api/db/scope.ts (createScopedDb({ userId })). No tenants, no orgs.
//
// Every table carries the four system fields (created_at/by, last_upd_at/by)
// per the conventions doc. Soft-delete (deleted_at) is intentionally omitted —
// none of these tables are soft-deletable at POC stage.

import { relations } from "drizzle-orm";
import {
  boolean,
  date,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  real,
  text,
  timestamp,
  unique,
  uuid,
} from "drizzle-orm/pg-core";
import type { PlanConfig } from "../shared/domain/study-plan";
import type { AiExplanation } from "../shared/domain/ai-eval";

// The four system audit columns present on every table without exception.
const systemFields = {
  createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow().notNull(),
  createdBy: uuid("created_by"),
  lastUpdAt: timestamp("last_upd_at", { withTimezone: true, mode: "string" })
    .defaultNow()
    .notNull(),
  lastUpdBy: uuid("last_upd_by"),
};

// ── Identity ────────────────────────────────────────────────────────────────

// People. `external_id` holds Clerk's user id. POC: rows are created manually
// via `pnpm db:create-user` (the Clerk webhook path is deferred).
export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  externalId: text("external_id").notNull().unique(),
  email: text("email"),
  name: text("name"),
  role: text("role").notNull().default("user"), // 'user' | 'admin'
  ...systemFields,
});

// ── Global catalog ───────────────────────────────────────────────────────────

// OAB exam questions — public, not user-scoped.
export const oabQuestions = pgTable(
  "oab_questions",
  {
    id: text("id").primaryKey(),
    questionText: text("question_text").notNull(),
    options: jsonb("options").$type<string[]>().notNull(),
    correctAnswer: text("correct_answer").notNull(),
    legalBasis: text("legal_basis"),
    explanation: text("explanation").notNull(),
    legislationLink: text("legislation_link"),
    legislationTitle: text("legislation_title"),
    difficulty: text("difficulty").notNull().default("medium"), // 'easy' | 'medium' | 'hard'
    discipline: text("discipline").notNull(),
    topic: text("topic").notNull(),
    examBoard: text("exam_board").notNull(), // 'FGV' | 'CESPE'
    year: integer("year").notNull(),
    phase: text("phase").notNull(), // '1st' | '2nd'
    aiExplanation: jsonb("ai_explanation").$type<AiExplanation>(), // nullable — absent until generated by admin
    ...systemFields,
  },
  (t) => [
    index("idx_oab_discipline").on(t.discipline),
    index("idx_oab_exam_board").on(t.examBoard),
    index("idx_oab_difficulty").on(t.difficulty),
    index("idx_oab_year").on(t.year),
  ],
);

// OAB 2ª-fase (prático-profissional / discursive) questions — public, not
// user-scoped. Each exam area's prova = one peça prático-profissional
// (order_index 0) + four questões discursivas (order_index 1–4). Kept in a
// separate table from oab_questions because these have no options and aren't
// graded by text-match — the whole MC pipeline (4-option UI, grading,
// simulations) assumes oab_questions, so discursive data lives apart.
export const oabDiscursiveQuestions = pgTable(
  "oab_discursive_questions",
  {
    id: text("id").primaryKey(),
    examLabel: text("exam_label").notNull(), // e.g. "XL Exame Unificado"
    examBoard: text("exam_board").notNull(), // 'FGV'
    year: integer("year").notNull(),
    phase: text("phase").notNull().default("2nd"), // always '2nd' for now
    area: text("area").notNull(), // DISCIPLINE LOV code (CIVIL_LAW, …) — candidate's chosen area
    questionType: text("question_type").notNull(), // QUESTION_TYPE LOV: 'PECA_PRATICA' | 'DISCURSIVE'
    orderIndex: integer("order_index").notNull(), // 0 = peça, 1–4 = discursivas
    statement: text("statement").notNull(), // situação-problema / enunciation
    modelAnswer: text("model_answer"), // padrão de resposta (official) — nullable
    maxPoints: real("max_points").notNull(), // 5.0 (peça) / 1.25 (discursiva)
    maxLines: integer("max_lines"), // e.g. 30 — nullable
    legalBasis: text("legal_basis"), // dispositivos do espelho — nullable
    topic: text("topic"), // short pt-BR topic label — nullable
    ...systemFields,
  },
  (t) => [
    index("idx_oab_disc_area").on(t.area),
    index("idx_oab_disc_exam").on(t.examLabel),
    index("idx_oab_disc_year").on(t.year),
  ],
);

// Tracks which 2ª-fase exam/area batches have been extracted into
// oab_discursive_questions — the admin "what do we already have" view. One row
// per (exam, area), upserted by the import save step. Global, not user-scoped.
export const oabDiscursiveImports = pgTable(
  "oab_discursive_imports",
  {
    id: text("id").primaryKey(), // imp-<examSlug>-<areaSlug>
    examLabel: text("exam_label").notNull(),
    examBoard: text("exam_board").notNull(),
    year: integer("year").notNull(),
    phase: text("phase").notNull().default("2nd"),
    area: text("area").notNull(), // DISCIPLINE LOV code
    itemCount: integer("item_count").notNull().default(0), // questions saved (peça + discursivas)
    modelAnswerCount: integer("model_answer_count").notNull().default(0), // how many have a padrão
    provaUrl: text("prova_url"), // source caderno PDF
    padraoUrl: text("padrao_url"), // source gabarito/padrão PDF
    ...systemFields, // lastUpdAt doubles as "last imported at"
  },
  (t) => [
    index("idx_oab_disc_imp_area").on(t.area),
    index("idx_oab_disc_imp_exam").on(t.examLabel),
  ],
);

// ── Per-user activity ─────────────────────────────────────────────────────────

export const userAnswers = pgTable(
  "user_answers",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    questionId: text("question_id")
      .notNull()
      .references(() => oabQuestions.id),
    userAnswer: text("user_answer").notNull(),
    correct: boolean("correct").notNull(),
    timeSpent: integer("time_spent").notNull(), // seconds
    ...systemFields,
  },
  (t) => [
    index("idx_user_answers_user").on(t.userId),
    index("idx_user_answers_question").on(t.questionId),
  ],
);

export const studySessions = pgTable(
  "study_sessions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    startedAt: timestamp("started_at", { withTimezone: true, mode: "string" })
      .defaultNow()
      .notNull(),
    endedAt: timestamp("ended_at", { withTimezone: true, mode: "string" }),
    totalQuestions: integer("total_questions").notNull().default(0),
    correctAnswers: integer("correct_answers").notNull().default(0),
    discipline: text("discipline").notNull(),
    difficulty: text("difficulty").notNull(), // 'easy' | 'medium' | 'hard'
    ...systemFields,
  },
  (t) => [index("idx_study_sessions_user").on(t.userId)],
);

// OAB 2ª-fase (discursive) study. Mirrors studySessions ↔ userAnswers but for
// essays: there are no options and no text-match grading, so the student
// self-scores against the official padrão (and may later request an AI score).
// A "prova" run (1 peça + 4 discursivas) groups its answers under one
// discursiveSession; single-question practice leaves sessionId null.
export const discursiveSessions = pgTable(
  "discursive_sessions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    examLabel: text("exam_label").notNull(), // snapshot of the answered prova
    area: text("area").notNull(), // DISCIPLINE LOV code
    year: integer("year").notNull(),
    startedAt: timestamp("started_at", { withTimezone: true, mode: "string" })
      .defaultNow()
      .notNull(),
    endedAt: timestamp("ended_at", { withTimezone: true, mode: "string" }),
    totalSelfScore: real("total_self_score"), // sum of per-item self-scores (nullable until graded)
    maxTotalPoints: real("max_total_points").notNull().default(10), // 5.0 peça + 4×1.25
    ...systemFields,
  },
  (t) => [index("idx_discursive_sessions_user").on(t.userId)],
);

// One student answer to a discursive question. Scores use `real` to match
// oab_discursive_questions.max_points (avoids the numeric→parseFloat dance the
// SM-2 columns need). AI columns are nullable and stay empty until the student
// requests an "Avaliar com IA" grade (computed off-Lambda via the central
// service, then persisted through discursive.saveAiGrade).
export const userDiscursiveAnswers = pgTable(
  "user_discursive_answers",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    questionId: text("question_id")
      .notNull()
      .references(() => oabDiscursiveQuestions.id),
    sessionId: uuid("session_id").references(() => discursiveSessions.id, {
      onDelete: "cascade",
    }), // null = single-question practice
    answerText: text("answer_text").notNull(),
    selfScore: real("self_score"), // 0..maxPoints, nullable until self-graded
    timeSpent: integer("time_spent").notNull(), // seconds
    aiScore: real("ai_score"), // 0..maxPoints, nullable until AI-graded
    aiFeedback: text("ai_feedback"),
    aiGradedAt: timestamp("ai_graded_at", { withTimezone: true, mode: "string" }),
    ...systemFields,
  },
  (t) => [
    index("idx_user_disc_answers_user").on(t.userId),
    index("idx_user_disc_answers_question").on(t.questionId),
    index("idx_user_disc_answers_session").on(t.sessionId),
  ],
);

// ── Per-user aggregates ───────────────────────────────────────────────────────

export const userPerformanceStats = pgTable("user_performance_stats", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id")
    .notNull()
    .unique()
    .references(() => users.id, { onDelete: "cascade" }),
  totalAnswered: integer("total_answered").notNull().default(0),
  totalCorrect: integer("total_correct").notNull().default(0),
  accuracy: numeric("accuracy").notNull().default("0"), // 0–100
  totalSessions: integer("total_sessions").notNull().default(0),
  averageTimePerQuestion: numeric("average_time_per_question").notNull().default("0"),
  ...systemFields,
});

export const disciplinePerformance = pgTable(
  "discipline_performance",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    discipline: text("discipline").notNull(),
    totalAnswered: integer("total_answered").notNull().default(0),
    totalCorrect: integer("total_correct").notNull().default(0),
    accuracy: numeric("accuracy").notNull().default("0"),
    ...systemFields,
  },
  (t) => [
    unique("uq_discipline_perf_user_discipline").on(t.userId, t.discipline),
    index("idx_discipline_perf_user").on(t.userId),
  ],
);

export const examBoardPerformance = pgTable(
  "exam_board_performance",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    examBoard: text("exam_board").notNull(), // 'FGV' | 'CESPE'
    totalAnswered: integer("total_answered").notNull().default(0),
    totalCorrect: integer("total_correct").notNull().default(0),
    accuracy: numeric("accuracy").notNull().default("0"),
    ...systemFields,
  },
  (t) => [
    unique("uq_exam_board_perf_user_board").on(t.userId, t.examBoard),
    index("idx_exam_board_perf_user").on(t.userId),
  ],
);

// ── Spaced repetition ────────────────────────────────────────────────────────

// Per-user SM-2 state for each question answered. Updated on every answer via
// sessions.record. Used by questions.reviewQueue to surface "due today" cards.
export const userQuestionStates = pgTable(
  "user_question_states",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    questionId: text("question_id")
      .notNull()
      .references(() => oabQuestions.id),
    interval: integer("interval").notNull().default(1), // days until next review
    repetitions: integer("repetitions").notNull().default(0), // successful reviews in a row
    easeFactor: numeric("ease_factor", { precision: 4, scale: 2 }).notNull().default("2.50"),
    nextReviewAt: timestamp("next_review_at", { withTimezone: true, mode: "string" })
      .defaultNow()
      .notNull(),
    lastCorrect: boolean("last_correct"),
    ...systemFields,
  },
  (t) => [
    unique("uq_user_question_state").on(t.userId, t.questionId),
    index("idx_uqs_user").on(t.userId),
    index("idx_uqs_next_review").on(t.userId, t.nextReviewAt),
  ],
);

// Global single-row config for the SM-2 algorithm — editable by admins.
// Always insert/update with id = 'default'. Read defaults from shared/domain/spaced-repetition.ts
// when the row doesn't exist yet.
export const spacedRepetitionConfig = pgTable("spaced_repetition_config", {
  id: text("id").primaryKey().default("default"),
  defaultEaseFactor: numeric("default_ease_factor", { precision: 4, scale: 2 })
    .notNull()
    .default("2.50"),
  minEaseFactor: numeric("min_ease_factor", { precision: 4, scale: 2 }).notNull().default("1.30"),
  easeFactorCorrectBonus: numeric("ease_factor_correct_bonus", { precision: 4, scale: 2 })
    .notNull()
    .default("0.10"),
  easeFactorWrongPenalty: numeric("ease_factor_wrong_penalty", { precision: 4, scale: 2 })
    .notNull()
    .default("0.20"),
  initialInterval: integer("initial_interval").notNull().default(1),
  secondInterval: integer("second_interval").notNull().default(6),
  ...systemFields,
});

// ── Goals & notifications ─────────────────────────────────────────────────────

export const userGoals = pgTable(
  "user_goals",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    discipline: text("discipline").notNull(),
    targetAccuracy: numeric("target_accuracy").notNull(), // 0–100
    ...systemFields,
  },
  (t) => [index("idx_user_goals_user").on(t.userId)],
);

export const goalNotifications = pgTable(
  "goal_notifications",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    goalId: uuid("goal_id")
      .notNull()
      .references(() => userGoals.id, { onDelete: "cascade" }),
    type: text("type").notNull(), // 'progress' | 'achieved' | 'warning'
    message: text("message").notNull(),
    read: boolean("read").notNull().default(false),
    ...systemFields,
  },
  (t) => [index("idx_goal_notif_user").on(t.userId), index("idx_goal_notif_goal").on(t.goalId)],
);

// ── Study plans ──────────────────────────────────────────────────────────────

export const studyPlans = pgTable(
  "study_plans",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    mode: text("mode").notNull(), // 'performance' | 'custom'
    deadlineDays: integer("deadline_days").notNull(), // 15|30|45|60|90|120
    targetDate: timestamp("target_date", { withTimezone: true, mode: "string" }).notNull(),
    questionsPerDay: integer("questions_per_day").notNull(),
    config: jsonb("config").$type<PlanConfig>().notNull(),
    ...systemFields,
  },
  (t) => [index("idx_study_plans_user").on(t.userId)],
);

// ── Notes & bookmarks ─────────────────────────────────────────────────────────

export const userQuestionNotes = pgTable(
  "user_question_notes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    questionId: text("question_id")
      .notNull()
      .references(() => oabQuestions.id),
    noteText: text("note_text").notNull(),
    ...systemFields,
  },
  (t) => [unique("uq_user_question_note").on(t.userId, t.questionId)],
);

export const userBookmarks = pgTable(
  "user_bookmarks",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    questionId: text("question_id")
      .notNull()
      .references(() => oabQuestions.id),
    ...systemFields,
  },
  (t) => [unique("uq_user_bookmark").on(t.userId, t.questionId)],
);

// ── Exam calendar ─────────────────────────────────────────────────────────────

// One entry per exam cycle (e.g. "46º EXAME DE ORDEM UNIFICADO"). Global, admin-managed.
export const examCalendars = pgTable(
  "exam_calendars",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    title: text("title").notNull(),
    note: text("note"), // e.g. "* Sujeito a alterações"
    active: boolean("active").notNull().default(true),
    sortOrder: integer("sort_order").notNull().default(0),
    ...systemFields,
  },
  (t) => [index("idx_exam_calendars_sort").on(t.sortOrder)],
);

// Individual milestones within a calendar (e.g. "Prova Objetiva – 1ª fase: 03/05/2026").
export const examCalendarEvents = pgTable(
  "exam_calendar_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    calendarId: uuid("calendar_id")
      .notNull()
      .references(() => examCalendars.id, { onDelete: "cascade" }),
    label: text("label").notNull(), // event name
    dateText: text("date_text").notNull(), // free-text date (supports ranges)
    eventDate: date("event_date"), // optional ISO YYYY-MM-DD for countdown
    sortOrder: integer("sort_order").notNull().default(0),
    ...systemFields,
  },
  (t) => [index("idx_exam_cal_events_cal").on(t.calendarId)],
);

// ── List of values (picklists) ────────────────────────────────────────────────

// Global reference catalog for dropdowns. `type` is an UPPER_SNAKE discriminator
// (DISCIPLINE, DIFFICULTY, EXAM_BOARD, PHASE); `code` is the English identifier
// stored in domain tables; `value` is the pt-BR display label. Not user-scoped.
export const listOfValues = pgTable(
  "list_of_values",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    type: text("type").notNull(),
    code: text("code").notNull(),
    value: text("value").notNull(),
    sortOrder: integer("sort_order").notNull().default(0),
    active: boolean("active").notNull().default(true),
    ...systemFields,
  },
  (t) => [unique("uq_lov_type_code").on(t.type, t.code), index("idx_lov_type").on(t.type)],
);

// ── AI buddy + billing tables ─────────────────────────────────────────────────
// Split into schema-ai.ts (max-lines); re-exported so import paths are stable.
export * from "./schema-ai";

// ── Relations ─────────────────────────────────────────────────────────────────

export const usersRelations = relations(users, ({ many, one }) => ({
  answers: many(userAnswers),
  sessions: many(studySessions),
  goals: many(userGoals),
  studyPlans: many(studyPlans),
  stats: one(userPerformanceStats),
  questionStates: many(userQuestionStates),
  notes: many(userQuestionNotes),
  bookmarks: many(userBookmarks),
}));

export const userQuestionStatesRelations = relations(userQuestionStates, ({ one }) => ({
  user: one(users, { fields: [userQuestionStates.userId], references: [users.id] }),
  question: one(oabQuestions, {
    fields: [userQuestionStates.questionId],
    references: [oabQuestions.id],
  }),
}));

export const studyPlansRelations = relations(studyPlans, ({ one }) => ({
  user: one(users, { fields: [studyPlans.userId], references: [users.id] }),
}));

export const userGoalsRelations = relations(userGoals, ({ one, many }) => ({
  user: one(users, { fields: [userGoals.userId], references: [users.id] }),
  notifications: many(goalNotifications),
}));

export const examCalendarsRelations = relations(examCalendars, ({ many }) => ({
  events: many(examCalendarEvents),
}));

export const examCalendarEventsRelations = relations(examCalendarEvents, ({ one }) => ({
  calendar: one(examCalendars, {
    fields: [examCalendarEvents.calendarId],
    references: [examCalendars.id],
  }),
}));

export const userQuestionNotesRelations = relations(userQuestionNotes, ({ one }) => ({
  user: one(users, { fields: [userQuestionNotes.userId], references: [users.id] }),
  question: one(oabQuestions, {
    fields: [userQuestionNotes.questionId],
    references: [oabQuestions.id],
  }),
}));

export const userBookmarksRelations = relations(userBookmarks, ({ one }) => ({
  user: one(users, { fields: [userBookmarks.userId], references: [users.id] }),
  question: one(oabQuestions, {
    fields: [userBookmarks.questionId],
    references: [oabQuestions.id],
  }),
}));
